# Generated by Django 3.2 on 2021-04-26 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paymentgateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_fund',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Purchase Date'),
            preserve_default=False,
        ),
    ]
