# Generated by Django 3.1 on 2021-06-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_account_withdrawal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='spn_roi_income',
            field=models.FloatField(default=0),
        ),
    ]
