# Generated by Django 3.2 on 2021-04-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_purchasedpackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackages',
            name='percemnt10',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchasedpackages',
            name='total_income',
            field=models.FloatField(default=0),
        ),
    ]
