# Generated by Django 3.2 on 2021-04-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_auto_20210429_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedpackages',
            old_name='percemnt10',
            new_name='percent10',
        ),
    ]
