# Generated by Django 3.2 on 2021-04-29 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0009_rename_percemnt10_purchasedpackages_percent10'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(default='-', max_length=40)),
                ('account_number', models.CharField(default='-', max_length=30)),
                ('branch_name', models.CharField(default='-', max_length=40)),
                ('ifsc_code', models.CharField(default='-', max_length=20)),
                ('bank_name', models.CharField(default='-', max_length=30)),
                ('nominee_name', models.CharField(default='-', max_length=30)),
                ('aadhar_number', models.CharField(default='-', max_length=12)),
                ('pan_number', models.CharField(default='-', max_length=10)),
                ('aadhar_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='adhar_pics')),
                ('pan_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pan_pics')),
                ('p_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('cheak', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
