# Generated by Django 3.2 on 2021-05-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0011_alter_purchasedpackages_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedpackages',
            name='days',
        ),
        migrations.AddField(
            model_name='purchasedpackages',
            name='day1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasedpackages',
            name='is_withdrawal',
            field=models.BooleanField(default=False),
        ),
    ]
