# Generated by Django 3.2 on 2021-05-01 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0013_allroiincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='allroiincome',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allroiincome',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allroiincome',
            name='package_amount',
            field=models.FloatField(default=0),
        ),
    ]
