# Generated by Django 3.2 on 2021-05-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0014_auto_20210501_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedpackages',
            name='day1',
            field=models.BooleanField(default=True),
        ),
    ]
