# Generated by Django 3.2 on 2021-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0018_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='trailer',
            field=models.CharField(default='', max_length=300),
        ),
    ]
