# Generated by Django 3.1 on 2021-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0021_purchasedpackages_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelincome',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
