# Generated by Django 3.1 on 2021-05-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0023_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allroionroiincome',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
