# Generated by Django 3.1 on 2021-05-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0024_auto_20210529_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allroionroiincome',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
