# Generated by Django 3.1 on 2021-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0026_auto_20210529_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
