# Generated by Django 3.1 on 2021-07-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0027_withdrawal_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='available_fund',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
